// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/service.go

// Package mock_service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAssignmentService is a mock of AssignmentService interface
type MockAssignmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAssignmentServiceMockRecorder
}

// MockAssignmentServiceMockRecorder is the mock recorder for MockAssignmentService
type MockAssignmentServiceMockRecorder struct {
	mock *MockAssignmentService
}

// NewMockAssignmentService creates a new mock instance
func NewMockAssignmentService(ctrl *gomock.Controller) *MockAssignmentService {
	mock := &MockAssignmentService{ctrl: ctrl}
	mock.recorder = &MockAssignmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAssignmentService) EXPECT() *MockAssignmentServiceMockRecorder {
	return m.recorder
}

// Healthy mocks base method
func (m *MockAssignmentService) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy
func (mr *MockAssignmentServiceMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockAssignmentService)(nil).Healthy))
}
